name: Ginza Hub
favicon: null
layout_spectrum: 0.49523
typography_spectrum: 0.8255419614724815
title: Self-service Co-working Space
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e8e6'
    - '#90b242'
    - '#4b4340'
    - '#96928f'
    - '#4c8f27'
  brandStrength: 0.14808328542858362
  lightness: 0.9368470057379454
  saturation: 0.9893599646165967
  rhythmicContrast: 0.6421555047854781
purpose: []
